[pytest]
asyncio_mode = strict
filterwarnings =
    error::DeprecationWarning
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
    ignore::DeprecationWarning:matplotlib.*
    ignore::DeprecationWarning:stable_baselines3.*
    ignore:Pyarrow will become a required dependency of pandas:DeprecationWarning
